DROP SCHEMA IF EXISTS `DiakDB`;

CREATE SCHEMA IF NOT EXISTS `DiakDB` DEFAULT CHARACTER SET utf8 ;

USE DiakDB;

CREATE TABLE IF NOT EXISTS User
(
	Id INT8 AUTO_INCREMENT PRIMARY KEY,
	UniqID VARCHAR(128) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL,
	Jelszo VARCHAR(255) NOT NULL,
	Role VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS Diak
(
	Id INT8 AUTO_INCREMENT PRIMARY KEY,
  UniqID VARCHAR(128) NOT NULL UNIQUE,
	Nev VARCHAR(255) NOT NULL,
  Kreditek INT NOT NULL
);

